### PR TITLE
fix: texture error displacement

### PR DESCRIPTION
**Pull request by EvanHsieh0415**
texture was wrongly shifted by 1px.

### CODE REVIEW

**Comment by JieningYu** [comment]
Does this issue exists on the Forge version?

**Comment by EvanHsieh0415** [comment]
No issue on the Forge version
image

**Comment by JieningYu** [comment]
bruh

**Review by EvanHsieh0415 — COMMENTED** [review]
LGTM

**Comment by JieningYu** [comment]
what

**Pull request merged**
